version: "3.5"
services:
  api:
    image: fastapi
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=2219499
      - DATABASE_USERNAME=postgres  
      - DATABASE_NAME=fast-api
      - SECRET_KEY=09d25e094faa65432456r466b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres


  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=2219499
      - POSTGRES_DB=fast-api
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
